global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'production'
    application: 'gestion-actividad'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # Backend API metrics
  - job_name: 'backend-api'
    static_configs:
      - targets: ['backend:3000']
    scrape_interval: 15s
    metrics_path: /api/metrics
    scrape_timeout: 10s
    honor_labels: true

  # Redis metrics (if redis_exporter is available)
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics
    scrape_timeout: 10s

  # SQL Server metrics (if sql_exporter is available)
  - job_name: 'sqlserver'
    static_configs:
      - targets: ['database:1433']
    scrape_interval: 60s
    metrics_path: /metrics
    scrape_timeout: 30s

  # Frontend Nginx metrics
  - job_name: 'nginx-frontend'
    static_configs:
      - targets: ['frontend:8080']
    scrape_interval: 30s
    metrics_path: /nginx_status
    scrape_timeout: 10s

  # Docker container metrics
  - job_name: 'docker'
    static_configs:
      - targets: ['host.docker.internal:9323']
    scrape_interval: 30s
    metrics_path: /metrics

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

# Storage configuration
storage:
  tsdb:
    path: /prometheus
    retention.time: 30d
    retention.size: 10GB

# Remote write configuration (for external monitoring)
# remote_write:
#   - url: "https://your-external-prometheus-endpoint/api/v1/write"
#     basic_auth:
#       username: "your-username"
#       password: "your-password"